# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tlb6700_connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_to_laser = QtWidgets.QPushButton(self.centralwidget)
        self.connect_to_laser.setGeometry(QtCore.QRect(129, 86, 75, 23))
        self.connect_to_laser.setObjectName("connect_to_laser")
        self.laser_connection_label = QtWidgets.QLabel(self.centralwidget)
        self.laser_connection_label.setGeometry(QtCore.QRect(219, 91, 131, 16))
        self.laser_connection_label.setObjectName("laser_connection_label")
        self.aichannel_label = QtWidgets.QLabel(self.centralwidget)
        self.aichannel_label.setGeometry(QtCore.QRect(23, 41, 51, 20))
        self.aichannel_label.setObjectName("aichannel_label")
        self.daq_connection_label = QtWidgets.QLabel(self.centralwidget)
        self.daq_connection_label.setGeometry(QtCore.QRect(219, 45, 191, 16))
        self.daq_connection_label.setObjectName("daq_connection_label")
        self.connect_to_daq = QtWidgets.QPushButton(self.centralwidget)
        self.connect_to_daq.setGeometry(QtCore.QRect(129, 41, 75, 23))
        self.connect_to_daq.setObjectName("connect_to_daq")
        self.aichannel_text = QtWidgets.QLineEdit(self.centralwidget)
        self.aichannel_text.setGeometry(QtCore.QRect(79, 41, 41, 20))
        self.aichannel_text.setObjectName("aichannel_text")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 431, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.connections_title = QtWidgets.QLabel(self.frame)
        self.connections_title.setGeometry(QtCore.QRect(10, 5, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connections_title.setFont(font)
        self.connections_title.setObjectName("connections_title")
        self.frame.raise_()
        self.connect_to_laser.raise_()
        self.laser_connection_label.raise_()
        self.aichannel_label.raise_()
        self.daq_connection_label.raise_()
        self.connect_to_daq.raise_()
        self.aichannel_text.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_to_laser.setText(_translate("MainWindow", "Connect"))
        self.laser_connection_label.setText(_translate("MainWindow", "laser not connected "))
        self.aichannel_label.setText(_translate("MainWindow", "ai channel:"))
        self.daq_connection_label.setText(_translate("MainWindow", "DAQ not connected "))
        self.connect_to_daq.setText(_translate("MainWindow", "Connect"))
        self.aichannel_text.setText(_translate("MainWindow", "ai2"))
        self.connections_title.setText(_translate("MainWindow", "Connections"))
